variables:
  SERVICES: dynamodb,dynamodbstreams,s3,kinesis,firehose,sqs
  AWS_CBOR_DISABLE: 'true'

stages:
  - test
  - publish

.unit:
  stage: test
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
  services:
    - name: localstack/localstack
      alias: localstack
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'

    - source gitlab/test.env

    - yum -y install unzip || true

    - curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o /tmp/awscli-bundle.zip
    - unzip /tmp/awscli-bundle.zip -d /tmp/awscli-bundle
    - /tmp/awscli-bundle/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4569; do sleep 1; done'
    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4570; do sleep 1; done'
    - dynamo/seed/seed.sh

    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4572; do sleep 1; done'
    - s3/seed/seed.sh

    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4568; do sleep 1; done'
    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4573; do sleep 1; done'
    - kinesis/seed/seed.sh

    # - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4575; do sleep 1; done'
    # - sns/seed/seed.sh

    - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4576; do sleep 1; done'
    - sqs/seed/seed.sh

    # - timeout 120 bash -c 'until echo > /dev/tcp/localstack/4579; do sleep 1; done'
    # - ses/seed/seed.sh
  script:
    - &unit ./gradlew test jacocoTestReport --stacktrace --scan
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    when: always
    expire_in: 1 day
    paths:
      - "*/*/build/reports"
      - "*/*/build/test-results"
      - "*/*/build/jacoco"
    reports:
      junit:
        - "*/*/build/test-results/test/TEST-*.xml"

unit@openjdk:8:
  extends: .unit
  image: openjdk:8
  script:
    - *unit
    - bash <(curl -s https://codecov.io/bash)

unit@openjdk:10:
  extends: .unit
  image: openjdk:10

unit@openjdk:11:
  extends: .unit
  image: openjdk:11

unit@openjdk:12:
  extends: .unit
  image: openjdk:12

unit@openjdk:13:
  extends: .unit
  image: openjdk:13

unit@openjdk:8-latest-aws-sdk:
  extends: .unit
  image: openjdk:8
  script:
    - export BY_DEV_MADHEAD_AWS_JUNIT5_USE_LATEST_AWS_SDK=true
    - *unit

gradle-version:
  stage: test
  image: openjdk:8
  script:
    - gradle_version=$(./gradlew --version | sed -rn 's/^Gradle (.+)$/\1/p')
    - latest_gradle_version=$(curl https://services.gradle.org/versions/current | python2 -c 'import json,sys;print json.load(sys.stdin)["version"]')
    - echo $gradle_version
    - echo $latest_gradle_version
    - '[[ $gradle_version == $latest_gradle_version ]]'
  allow_failure: true

copyright:
  stage: test
  image: bash:latest
  script:
    - copyright_year=$(sed -n 's/Copyright (c) \([[:digit:]]\{4\}\) madhead <siarhei.krukau@gmail.com>/\1/p' LICENSE)
    - current_year=$(date +%Y)
    - echo $copyright_year
    - echo $current_year
    - '[[ $copyright_year == $current_year ]]'
  allow_failure: true

bintray:
  stage: publish
  image: openjdk:8
  script:
    - ./gradlew bintrayUpload
  only:
    - master
  dependencies: []
